### ISSUE TITLE
提供一个背景

### ISSUE THREAD

**Issue by wangdongdong123456** [ikun-svelte/ikun-ui#113]
### Description

![1692581693599_a3279679d17f6d2be2869801129aaeb7_143241r9w5p6q0p6e8eqdc](https://github.com/ikun-svelte/ikun-ui/assets/94151171/3a768c1c-2759-483f-8494-16b4124a3dbb)

**Comment by baiwusanyu-c** [comment]
The whole point is abstract, it's so realistic, I have beak fears..
