### ISSUE TITLE
与其贬低他人，不如好好工作

### ISSUE THREAD

**Issue by ckcoding** [ikun-svelte/ikun-ui#13]
<img width="1679" alt="image" src="https://github.com/ikun-svelte/ikun-ui/assets/63556878/87ab8b29-419b-4b51-8346-eb8e69bfa360">

**Comment by baiwusanyu-c** [comment]
合理

**Comment by YangYongAn** [comment]
你的状态栏是什么！！！

**Comment by wangdongdong123456** [comment]
![84FD7BE4-71CC-4532-88F5-33160DA04AC4](https://github.com/ikun-svelte/ikun-ui/assets/94151171/ebf80661-0aef-455a-a6b9-ec722231c384)
只因

**Comment by wangdongdong123456** [comment]
![84FD7BE4-71CC-4532-88F5-33160DA04AC4](https://github.com/ikun-svelte/ikun-ui/assets/94151171/ebf80661-0aef-455a-a6b9-ec722231c384)
只因

**Comment by toplyb** [comment]
还得是看网友啊，泰苦辣

**Comment by mayingjie123** [comment]
> 你的状态栏是什么！！！

考验视力是吧

**Comment by shaohao123** [comment]
看来我眼神还可以
