### ISSUE TITLE
[BUG] -  @ikun-ui/utils npm 版本低，无法install

### ISSUE THREAD

**Issue by a145789** [ikun-svelte/ikun-ui#140]
### Describe the bug

```shell
pnpm add @ikun-ui/core && pnpm add -D unocss && pnpm add -D @ikun-ui/preset
```

> ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @ikun-ui/utils@0.0.9-beta.2
This error happened while installing the dependencies of @ikun-ui/core@0.0.9-beta.2
The latest release of @ikun-ui/utils is "0.0.9-beta.1".
If you need the full list of all 7 published versions run "$ pnpm view @ikun-ui/utils versions".
Progress: resolved 214, reused 213, downloaded 0, added 0

[@ikun-ui/utils](https://www.npmjs.com/package/@ikun-ui/utils?activeTab=readme)

坤坤坤，已经迫不及待的想体验一下哥哥的UI了

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/ikun-svelte/ikun-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://ikun-ui.netlify.app/).
- [X] Check that there isn't [already an issue](https://github.com/ikun-svelte/ikun-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a ikun-ui issue and not a framework-specific issue. For example, if it's a Svelte SFC related bug, it should likely be reported to https://github.com/sveltejs/svelte instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by baiwusanyu-c** [comment]
Try with latest version
