### ISSUE TITLE
[BUG] - KInput 设置bind:value 不能实时更新

### ISSUE THREAD

**Issue by a145789** [ikun-svelte/ikun-ui#146]
### Describe the bug

```ts
<script lang="ts">
import { KInput } from "@ikun-ui/input"
let text = ""
function Input(){
 console.log(text) // 始终为 ""
}
</script>
<main>
 <KInput
     on:input={Input}
      bind:value={text}
      cls="mx-2"
    />
</main>
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.25931
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
    Memory: 4.73 GB / 15.92 GB
  Binaries:
    Node: 18.15.0 - D:\node\node.EXE
    Yarn: 1.22.19 - D:\node-store\.pnpm-store\yarn.CMD
    npm: 9.5.0 - D:\node\npm.CMD
  Browsers:
    Edge: Chromium (116.0.1938.62)
    Internet Explorer: 11.0.25931.1000
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/ikun-svelte/ikun-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://ikun-ui.netlify.app/).
- [X] Check that there isn't [already an issue](https://github.com/ikun-svelte/ikun-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a ikun-ui issue and not a framework-specific issue. For example, if it's a Svelte SFC related bug, it should likely be reported to https://github.com/sveltejs/svelte instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vtrbo** [comment]
It will be fixed in the next version.
