### ISSUE TITLE
[Feature Request] - input 组件暴露 compositionstart compositionend 事件

### ISSUE THREAD

**Issue by a145789** [ikun-svelte/ikun-ui#149]
### Clear and concise description of the problem

对于中文用户的搜索功能，并不希望搜索在输入法操作时字符，

### Suggested solution

暴露 compositionstart compositionend 事件
对于用户更方便一点的话希望有一个 onCompositionInput 事件，组件内部封装这种操作

### Describe alternatives you've considered

无

**Comment by a145789** [comment]
What do you think of the onCompositionInput event? If it's possible, I could submit a PR for it.

**Comment by baiwusanyu-c** [comment]
just do it！
