### ISSUE TITLE
[BUG] Button component style error

### ISSUE THREAD

**Issue by baiwusanyu-c** [ikun-svelte/ikun-ui#159]
### Describe the bug

![image](https://github.com/ikun-svelte/ikun-ui/assets/32354856/b412f2cd-e729-462a-95d5-ecb737819af1)

Related： #144 

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/ikun-svelte/ikun-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://ikun-ui.netlify.app/).
- [X] Check that there isn't [already an issue](https://github.com/ikun-svelte/ikun-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a ikun-ui issue and not a framework-specific issue. For example, if it's a Svelte SFC related bug, it should likely be reported to https://github.com/sveltejs/svelte instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by baiwusanyu-c** [comment]
![image](https://github.com/ikun-svelte/ikun-ui/assets/32354856/3a52f0b3-a839-4bb0-98c9-fa015c2c5ec7)

**Comment by vtrbo** [comment]
The fonts are sm, base, lg, the unit is rem. The icon is 12px, 16px, 20px, the unit is px. If you want to fix it, you need to adjust the font to 12, 16, 20px. I try fix it.
