### ISSUE TITLE
[BUG] Blinks when the spin component disappears

### ISSUE THREAD

**Issue by baiwusanyu-c** [ikun-svelte/ikun-ui#165]
### Describe the bug

![spin](https://github.com/ikun-svelte/ikun-ui/assets/32354856/266f93d7-6de6-4171-a3ca-378be0232057)

Blinks when the spin component disappears

### System Info

```Shell
latest
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/ikun-svelte/ikun-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://ikun-ui.netlify.app/).
- [X] Check that there isn't [already an issue](https://github.com/ikun-svelte/ikun-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a ikun-ui issue and not a framework-specific issue. For example, if it's a Svelte SFC related bug, it should likely be reported to https://github.com/sveltejs/svelte instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vtrbo** [comment]
I tried adding a timer of 300ms when the value is false in mask component, which can fix this problem, but I'm not sure if it's elegant.

```svelte
$: if (value) {
		setParent();
	} else {
      setTimeout(()=> {
          reset();
		}, 300)
	}

```

**Comment by baiwusanyu-c** [comment]
There seems to be no other way. Svelte does not provide a hook for the end of the animation. This causes an error to occur when operating the dom before the animation ends.
