### ISSUE TITLE
[BUG] button component type error

### ISSUE THREAD

**Issue by baiwusanyu-c** [ikun-svelte/ikun-ui#166]
### Describe the bug

<img width="979" alt="image" src="https://github.com/ikun-svelte/ikun-ui/assets/32354856/a3c75339-b047-4913-95d4-e365d9406f87">

### System Info

```Shell
latest
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/ikun-svelte/ikun-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://ikun-ui.netlify.app/).
- [X] Check that there isn't [already an issue](https://github.com/ikun-svelte/ikun-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a ikun-ui issue and not a framework-specific issue. For example, if it's a Svelte SFC related bug, it should likely be reported to https://github.com/sveltejs/svelte instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by baiwusanyu-c** [comment]
cc/ @vtrbo

**Comment by vtrbo** [comment]
> cc/ @vtrbo

Why does my webstorm not report an error, do I need to set it?

**Comment by baiwusanyu-c** [comment]
![image](https://github.com/ikun-svelte/ikun-ui/assets/32354856/c9280424-e7b3-4467-93ed-226b1e4c06e5)
![image](https://github.com/ikun-svelte/ikun-ui/assets/32354856/18feec84-068a-465d-b1c9-f0c921637a86)

**Comment by baiwusanyu-c** [comment]
![image](https://github.com/ikun-svelte/ikun-ui/assets/32354856/cd17d866-99b4-4eb2-972d-17734239b9aa)

**Comment by baiwusanyu-c** [comment]
Webstorm needs to be restarted to take effect
