### ISSUE TITLE
[Enhance] Change pre-commit command

### ISSUE THREAD

**Issue by sakanjo** [ikun-svelte/ikun-ui#193]
### Description

When committing to github simply `pre-commit` hook runs `pnpm run format && pnpm run lint` which formats and lints all the files even **non-staged** one, which formats almost 264 files and commits them.

The good way to fix this issue by removing `pnpm run format && pnpm run lint` and instead use [lint-staged](https://github.com/okonet/lint-staged).

**Comment by baiwusanyu-c** [comment]
welcome pr～～ 😊
