### ISSUE TITLE
[Enhance] Replace class-name.ts with clsx

### ISSUE THREAD

**Issue by sakanjo** [ikun-svelte/ikun-ui#195]
### Describe the bug

`createCls([false])` will raise an exception.

I suggest using [clsx](https://www.npmjs.com/package/clsx) since it's already handling those cases and it's a great package, and if so please let me know so I can open a PR.

### Reproduction

`createCls([false])`

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/ikun-svelte/ikun-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://ikun-ui.netlify.app/).
- [X] Check that there isn't [already an issue](https://github.com/ikun-svelte/ikun-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a ikun-ui issue and not a framework-specific issue. For example, if it's a Svelte SFC related bug, it should likely be reported to https://github.com/sveltejs/svelte instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by baiwusanyu-c** [comment]
`createCls([false])` is not a common use case since `createCls` is an internal method, but `clsx` looks great and I think it can be used

**Comment by sakanjo** [comment]
I don't mean to use false inside array, but the array itself it doesn't work, while if you worked with @vuejs classes before you will see that it supports classes and other formats just like `clsx` does.
