### ISSUE TITLE
后续会有vue3/react版本吗？作为一名ikun想参与进来，但是不会Svelte

### ISSUE THREAD

**Issue by huangshihao123** [ikun-svelte/ikun-ui#206]
### Description

后续会有vue3/react版本吗？作为一名ikun想参与进来，但是不会Svelte
Will there be a vue3/react version in the future? As an ikun, I want to get involved, but I don't know Svelte

**Comment by baiwusanyu-c** [comment]
不会有 vue3/react 版本，svelte其实很简单，模板语法、计算属性、响应式变量这些我觉得一两天就能上手
