### ISSUE TITLE
开庭的时候记得带上你的UI

### ISSUE THREAD

**Issue by YAANLE** [ikun-svelte/ikun-ui#235]
### Description

![image](https://camo.githubusercontent.com/fe3e167e0b8215448746497f48b4eb415579e8a192777c5bc3d5f12d9b8b4f59/68747470733a2f2f7473312e636e2e6d6d2e62696e672e6e65742f74682f69642f522d432e36383534646565383162663464316666363931663466343536306534373837323f72696b3d736a504e61314653686776597077267269753d687474702533612532662532667069632e646f776e79692e636f6d25326675706c6f6164253266323031392d352532663230313935313431353332353837353937302e6a70672665686b3d3734467a316a6e614d5937786c6d5538693678496f42523365336a68643955434936496837395a67555449253364267269736c3d267069643d496d6752617726723d30)

**Comment by pkc918** [comment]
移步 Discussion 😌
