### ISSUE TITLE
[BUG] - The rate component is started in the document, and unocss reports a warning.

### ISSUE THREAD

**Issue by baiwusanyu-c** [ikun-svelte/ikun-ui#250]
### Describe the bug

![image](https://github.com/ikun-svelte/ikun-ui/assets/32354856/69839af3-2261-4967-a3f2-f124e94a9a23)

The rate component is started in the document, and unocss reports a warning.

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/ikun-svelte/ikun-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://ikun-ui.netlify.app/).
- [X] Check that there isn't [already an issue](https://github.com/ikun-svelte/ikun-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a ikun-ui issue and not a framework-specific issue. For example, if it's a Svelte SFC related bug, it should likely be reported to https://github.com/sveltejs/svelte instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vtrbo** [comment]
After reviewing, I found the minimum reproducible case as follows.

code

```svelte
<script lang="ts">
	import { getPrefixCls } from '@ikun-ui/utils';
	import { KIcon } from '@ikun-ui/icon';

	export let icon = 'i-carbon-star';
	export let attrs = {};

	const prefixCls = getPrefixCls('rate');
</script>

<KIcon cls={prefixCls} {...attrs} icon="i-carbon-settings"></KIcon>
```

output

<img width="400" alt="image" src="https://github.com/ikun-svelte/ikun-ui/assets/59214241/e63b5c46-f646-4499-a18e-1299e89b1913">

So, I currently don't have any options to fix it.
