### ISSUE TITLE
negative comment   ---No chicken

### ISSUE THREAD

**Issue by Hi-Mr-Wind** [ikun-svelte/ikun-ui#280]
### Description

Your name doesn't match the reality.   
 I didn't find the chicken element.   
It's a chicken, after all, Not a person.
And why is there no documentation in Chinese?

**Comment by so1ve** [comment]
This project aimed to be a general, usable component library for svelte. Name is just a name. If you think some 🐔 should beadded to this library, feel free to contribute this feature as an easter egg, or add a feature flag for it.
