### ISSUE TITLE
[Feature Request] - Increase Form Components

### ISSUE THREAD

**Issue by vtrbo** [ikun-svelte/ikun-ui#284]
## Three Sizes Of Form Components

| Component | Status |
| --------- | ------ |
| Checkbox  | ✅ #285 |
| Switch    |  ✅ #286 |
| Radio     | ✅ #287 |
| Rate      | ✅ #288 |
| Slider    |  ✅ #339   |

## Increase Slider

| Enhance      | Status |
| ------------ | ------ |
| Range Slider | move #342   |

**Comment by baiwusanyu-c** [comment]
select会有大的修改，建议现在不动

**Comment by vtrbo** [comment]
> select会有大的修改，建议现在不动

OK

**Comment by ngogiaphat** [comment]
Why can't I format code files in **.svelte** format in components, play, e2e folders with Prettier ?

**Comment by baiwusanyu-c** [comment]
> Why can't I format code files in **.svelte** format in components, play, e2e folders with Prettier ?

There seems to be a problem with the prettier configuration, I will find time to fix it
