### ISSUE TITLE
[BUG] - Error occurs when launching the development server.

### ISSUE THREAD

**Issue by cat394** [ikun-svelte/ikun-ui#293]
### Describe the bug

In the Stackblitz environment, I created a SvelteKit project and followed the installation instructions for ikun-ui. 
When I tried to launch the development server, I encountered an error. This issue also occurs in my local environment. 
Here is a screenshot of the error 👇
![スクリーンショット 2023-10-10 114507](https://github.com/ikun-svelte/ikun-ui/assets/91322302/2e142599-9e76-4d6d-b131-c4242b987ffa)

I would appreciate it if you could let me know if there is anything wrong.

### Reproduction

https://stackblitz.com/edit/sveltekit-ikunui

### System Info

```Shell
windows11, brave browser
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/ikun-svelte/ikun-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://ikun-ui.netlify.app/).
- [X] Check that there isn't [already an issue](https://github.com/ikun-svelte/ikun-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a ikun-ui issue and not a framework-specific issue. For example, if it's a Svelte SFC related bug, it should likely be reported to https://github.com/sveltejs/svelte instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by baiwusanyu-c** [comment]
The problem stems from the changes in #174

**Comment by baiwusanyu-c** [comment]
Try using the latest version

**Comment by cat394** [comment]
I just tried it and it worked fine! 

Thank you for your courteous and quick response.

**Comment by baiwusanyu-c** [comment]
`ikun-ui` is still in its infancy and there will be some problems, so thank you for your feedback
