### ISSUE TITLE
[Feature Request] - Drag Component

### ISSUE THREAD

**Issue by pkc918** [ikun-svelte/ikun-ui#325]
### Clear and concise description of the problem

 Is there a plan to release this component?

**Comment by baiwusanyu-c** [comment]
cc: https://alfred-skyblue.github.io/svelte-draggable-plus

**Comment by baiwusanyu-c** [comment]
There are no relevant plans in the near future. You can refer to the functions provided by `svelte-draggable-plus`. If it is powerful enough, I don’t think it is necessary to make an identical component. Maybe we can integrate it into `ikun-ui`.
