### ISSUE TITLE
墙裂建议出个vue版的，sevlte都是国外用的多，话说老外也懂ikun吗

### ISSUE THREAD

**Issue by xintianyou** [ikun-svelte/ikun-ui#33]

**Comment by ckcoding** [comment]
老外也说iKun话

**Comment by heerey525** [comment]
全世界都有iKun

**Comment by Sunshop** [comment]
有一起出 vue3 版本的 兄弟吗？coder 永不为奴

**Comment by LAINE001** [comment]
看看这个，https://laine001.github.io/ikun-ui/

**Comment by baiwusanyu-c** [comment]
There is no other version plan for the time being. The main purpose of this library is to enrich the svelte ecology

**Comment by xintianyou** [comment]
> 看看这个，https://laine001.github.io/ikun-ui/



> 看看这个，https://laine001.github.io/ikun-ui/
new bee

**Comment by xintianyou** [comment]
> There is no other version plan for the time being. The main purpose of this library is to enrich the svelte ecology

ok
