### ISSUE TITLE
[BUG] - 引入组件库组件内部使用的icon无法显示

### ISSUE THREAD

**Issue by chrishuangjun** [ikun-svelte/ikun-ui#331]
### Describe the bug

显示出来的modal组件的关闭icon无法正常显示
App.svelte组件：
<script lang="ts">
  import svelteLogo from './assets/svelte.svg'
  import viteLogo from '/vite.svg'
  import Counter from './lib/Counter.svelte'
  import { KModal } from "@ikun-ui/core";
    import 'virtual:uno.css'
    let show = true
</script>

<main>
  <div>
    <a href="https://vitejs.dev" target="_blank" rel="noreferrer">
      <img src={viteLogo} class="logo" alt="Vite Logo" />
    </a>
    <a href="https://svelte.dev" target="_blank" rel="noreferrer">
      <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
    </a>
  </div>
  <h1>Vite + Svelte</h1>

  <div class="card">
    <Counter />
  </div>

  <p>
    Check out <a href="https://github.com/sveltejs/kit#readme" target="_blank" rel="noreferrer">SvelteKit</a>, the official Svelte app framework powered by Vite!
  </p>

  <p class="read-the-docs">
    Click on the Vite and Svelte logos to learn more
  </p>
  <KModal title="Jean-Christophe"
        on:close={()=> show = false}
        show={show}>
    <p class="text-center !my-2">
        🥵 Sadness makes people more acute.
    </p>
</KModal>
</main>

<style>
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
  }
  .logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
  }
  .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00aa);
  }
  .read-the-docs {
    color: #888;
  }
</style>

unocss.config.ts文件：
import { defineConfig, presetAttributify, presetIcons, presetUno } from 'unocss';
import { presetIkun, getCSSPreflights, getSafeList } from '@ikun-ui/preset';

export default defineConfig({
    presets: [presetUno(), presetAttributify(), presetIcons(), presetIkun()],
    safelist: [...getSafeList()],
    preflights: [
        {
            layer: 'base',
            getCSS: () => `:root {${getCSSPreflights()}}`
        }
    ]
});

vite.config.ts文件：
import { defineConfig, type Plugin } from 'vite'
import { svelte } from '@sveltejs/vite-plugin-svelte'
import UnoCSS from 'unocss/vite'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    svelte(),
    UnoCSS(),
    {
      name: 'compatible:svelte:kit',
      post: 'pre',
      enforce: 'pre',
      resolveId(id: string) {
        if (id === 'esm-env') return '\0esm-env';
      },
      load(id: string) {
        if (id === '\0esm-env') return 'export const BROWSER = true';
      }
    } as Plugin
  ],
})

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/ikun-svelte/ikun-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://ikun-ui.netlify.app/).
- [X] Check that there isn't [already an issue](https://github.com/ikun-svelte/ikun-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a ikun-ui issue and not a framework-specific issue. For example, if it's a Svelte SFC related bug, it should likely be reported to https://github.com/sveltejs/svelte instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by baiwusanyu-c** [comment]
建议使用 svelte-kit

**Comment by chrishuangjun** [comment]
[svelte-demo.zip](https://github.com/ikun-svelte/ikun-ui/files/13343392/svelte-demo.zip)
这是我的工程demo，麻烦帮忙看看

**Comment by pkc918** [comment]
我用你的代码运行，也没问题啊

**Comment by baiwusanyu-c** [comment]
试试这个吧，部分原子类并没有提取出来，这使得被unocss编译器忽略了
```
import { defineConfig, presetAttributify, presetIcons, presetUno } from 'unocss';
import { presetIkun, getCSSPreflights, getSafeList } from '@ikun-ui/preset';

export default defineConfig({
    presets: [presetUno(), presetAttributify(), presetIcons(), presetIkun()],
    safelist: [
      ...getSafeList(),
      ...[
        'i-carbon-close-outline',
        'i-carbon-circle-dash',
        'i-carbon-arrow-up',
        'i-carbon-checkmark',
        'i-carbon-subtract',
        'i-carbon-chevron-right',
        'i-carbon:close-outline',
        'i-carbon-view-off',
        'i-carbon-view',
        'i-carbon-close',
        'i-carbon-chevron-left',
        'i-carbon-settings',
        'i-carbon:radio-button-checked',
        'i-carbon-chevron-down',
        'i-carbon-overflow-menu-horizontal',
        'i-carbon-page-last',
        'i-carbon-page-first',
        'rotate-180',
        'px-0',
        'w-full',
        'flex',
        'inline-flex',
        'ml-1',
        'ml-2',
        'mr-2',
        'text-white',
        'rotate-90',
        'right-0',
        'justify-start',
        'justify-end',
        'left-0'
      ],
    ],
    preflights: [
        {
            layer: 'base',
            getCSS: () => `:root {${getCSSPreflights()}}`
        }
    ]
});

```

**Comment by chrishuangjun** [comment]
加上上面的配置就可以了，应该是图标的class被unocss忽略掉了，感谢大佬
