### ISSUE TITLE
[BUG] - I get a warning when installing dependencies

### ISSUE THREAD

**Issue by vtrbo** [ikun-svelte/ikun-ui#349]
### Describe the bug

<img width="445" alt="image" src="https://github.com/ikun-svelte/ikun-ui/assets/59214241/cb0f8a55-fff1-470e-9bfd-212b3360cff7">

### System Info

```Shell
System:
    OS: macOS 12.6.5
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 831.36 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.9.2 - ~/.nvm/versions/node/v18.17.1/bin/pnpm
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 15.6.1
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/ikun-svelte/ikun-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://ikun-ui.netlify.app/).
- [X] Check that there isn't [already an issue](https://github.com/ikun-svelte/ikun-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a ikun-ui issue and not a framework-specific issue. For example, if it's a Svelte SFC related bug, it should likely be reported to https://github.com/sveltejs/svelte instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by baiwusanyu-c** [comment]
svelte 上游依赖问题

**Comment by vtrbo** [comment]
> svelte 上游依赖问题

嗯是的，这个留不留？
