### ISSUE TITLE
Feature: Request supports for Vue.js

### ISSUE THREAD

**Issue by LikeDreamwalker** [ikun-svelte/ikun-ui#38]

**Comment by LAINE001** [comment]
See this. https://laine001.github.io/ikun-ui/

**Comment by baiwusanyu-c** [comment]
There is no other version plan for the time being. The main purpose of this library is to enrich the svelte ecology

**Comment by LikeDreamwalker** [comment]
> There is no other version plan for the time being. The main purpose of this library is to enrich the svelte ecology
那行吧，开庭的时候记得带上电脑😈
