### ISSUE TITLE
WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

### ISSUE THREAD

**Issue by bayaderpack** [ikun-svelte/ikun-ui#398]
### Description

I must install every component manually

https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition

![image](https://github.com/ikun-svelte/ikun-ui/assets/152959097/2144e42a-6cd2-4c89-96ff-c5a915d3c4d3)

**Comment by baiwusanyu-c** [comment]
You can ignore it for now. I have modified this question, but I haven’t released a new version yet. In addition, some components in the document may not have been released. I’m really sorry.
