### ISSUE TITLE
[BUG] - @ikun-ui/flex is not in the npm registry

### ISSUE THREAD

**Issue by keilestone** [ikun-svelte/ikun-ui#401]
### Describe the bug

安装@ikun-ui/flex

报错@ikun-ui/flex is not in the npm registry, or you have no permission to fetch it

### Used Package Manager

pnpm

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/ikun-svelte/ikun-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://ikun-ui.netlify.app/).
- [X] Check that there isn't [already an issue](https://github.com/ikun-svelte/ikun-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a ikun-ui issue and not a framework-specific issue. For example, if it's a Svelte SFC related bug, it should likely be reported to https://github.com/sveltejs/svelte instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by pkc918** [comment]
@baiwusanyu-c

**Comment by pkc918** [comment]
He might have forgotten to release it.

**Comment by baiwusanyu-c** [comment]
Sorry for not replying in time due to being very busy recently, it will be released in v0.2.0
