### ISSUE TITLE
为什么没有样式，帮忙看一下，折腾了好久

### ISSUE THREAD

**Issue by endison1986** [ikun-svelte/ikun-ui#444]
### Description

[NoStyle.zip](https://github.com/user-attachments/files/15530387/NoStyle.zip)

**Comment by baiwusanyu-c** [comment]
![Uploading image.png…]()

**Comment by endison1986** [comment]
谢谢，可以了
另外再弱弱的问一句，ikun-ui可以使用javascript的svelte么，我使用svelte的脚手架构建的项目，选择javascript的环境，启动成功，但访问页面的时候会报`Unexpected token`，在`import type {`这边

**Comment by pkc918** [comment]
> 谢谢，可以了 另外再弱弱的问一句，ikun-ui可以使用javascript的svelte么，我使用svelte的脚手架构建的项目，选择javascript的环境，启动成功，但访问页面的时候会报`Unexpected token`，在`import type {`这边 @baiwusanyu-c

如果能给在线案例，可能更方便

**Comment by endison1986** [comment]
[my-app.zip](https://github.com/user-attachments/files/15543254/my-app.zip)
![image](https://github.com/ikun-svelte/ikun-ui/assets/7878324/9152c33d-bfd0-43cf-b50b-a370451e7b5a)

**Comment by endison1986** [comment]
@pkc918 @baiwusanyu-c 可以帮忙看一下么

**Comment by pkc918** [comment]
https://stackblitz.com/

**Comment by endison1986** [comment]
https://stackblitz.com/edit/sveltejs-kit-template-default-qkxhwe?file=src%2Froutes%2F%2Blayout.svelte
@pkc918 谢谢

**Comment by baiwusanyu-c** [comment]
暂时只支持 ts，目前是SFC源码发包，最后引用是 ts 版本的源码
