### ISSUE TITLE
[BUG] - YOUR_ISSUE_TITLE_HERE_REPLACE_ME

### ISSUE THREAD

**Issue by a1113590485** [ikun-svelte/ikun-ui#449]
### Describe the bug

```
<script>
	import { KButton } from '@ikun-ui/button';
	import { KButtonGroup } from '@ikun-ui/button-group';
</script>
<div class="flex items-center flex-wrap">
	<KButton type="info" cls="mx-2">info</KButton>
	<KButton type="error" cls="mx-2">error</KButton>
	<KButton type="success" cls="mx-2">success</KButton>
	<KButton type="primary" cls="mx-2">primary</KButton>
	<KButton type="warning" cls="mx-2">warning</KButton>
</div>
```

运行官方案例时，会直接报错
```
1 |  <script lang="ts">
 2 |    import type { KButtonGroupPropsInner, KButtonProps } from './types';
                    ^
 3 |    import { createEventDispatcher, getContext } from 'svelte';
 4 |    import { KIcon } from '@ikun-ui/icon';
```
 环境使用的是sveltekit创建的js工程项目，是否是缺少了某项引入，导致的错误

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/ikun-svelte/ikun-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://ikun-ui.netlify.app/).
- [X] Check that there isn't [already an issue](https://github.com/ikun-svelte/ikun-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a ikun-ui issue and not a framework-specific issue. For example, if it's a Svelte SFC related bug, it should likely be reported to https://github.com/sveltejs/svelte instead.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by baiwusanyu-c** [comment]
应该是ts语法导致，组件以 sfc 方式发包，暂时没有支持到 js
