### ISSUE TITLE
如何加入爱坤团队一起打造爱坤UI

### ISSUE THREAD

**Issue by YuLinXi** [ikun-svelte/ikun-ui#52]
如题，爱坤多年，希望能加入开源

**Comment by baiwusanyu-c** [comment]
https://github.com/ikun-svelte/ikun-ui/discussions/50
Use pr as a stepping stone

**Comment by YuLinXi** [comment]
> #50 Use pr as a stepping stone

ok

**Comment by moushicheng** [comment]
笑死我了，有空我也来看看这个

**Comment by lively-krishnan** [comment]
+1

**Comment by chengYuanXiang11** [comment]
我是ikun，黑我家giegie，蒸虾头，食不食油饼，我要给你寄绿石涵
