### ISSUE TITLE
文档网站怎么打不开了

### ISSUE THREAD

**Issue by 1259364843** [ikun-svelte/ikun-ui#68]
### Description

文档网站怎么打不开了
![image](https://github.com/ikun-svelte/ikun-ui/assets/24851375/247d84cc-5bc9-4371-9fee-a00e717d7ab5)

**Comment by baiwusanyu-c** [comment]
需要梯子哦

**Comment by baiwusanyu-c** [comment]
目前国内部分宽带开了梯子也会屏蔽，可以尝试移动热点
