### ISSUE TITLE
Feature: 加一个 kunkun 打篮球的 loading 动画吧

### ISSUE THREAD

**Issue by NWYLZW** [ikun-svelte/ikun-ui#7]

**Comment by haobarry** [comment]
赶紧做一个

**Comment by baiwusanyu-c** [comment]
可以加一个篮球滚动的 loading

**Comment by NWYLZW** [comment]
> 可以加一个篮球滚动的 loading

组件的含鸡量有点低，可以多整点（（（

**Comment by guobin211** [comment]
附议

**Comment by ckcoding** [comment]
不是，你们这些小黑子都什么意思啊

**Comment by cl-cc** [comment]
附议

**Comment by bigxixi** [comment]
优化了一下头图体积(192kb -> 3kb)，加了点动画
![logo-withAni](https://github.com/ikun-svelte/ikun-ui/assets/22438240/4edc12e3-7280-4bd5-9d25-a6a14e063bad)

**Comment by blockmood** [comment]
@bigxixi  头呢？？

**Comment by msidolphin** [comment]
附议

**Comment by wangdongdong123456** [comment]
单走一个6

**Comment by songzhanpeng** [comment]
> 优化头部图体积(192kb -> 3kb)，加了点动画 ![标志-withAni](https://user-images.githubusercontent.com/22438240/258717075-1c071b29-c4d5-4f75-9ca6-3cdcf9b73151.svg)

大佬，篮球能优化一下嘛，加个条纹

**Comment by quiet-dog** [comment]
非常帅

**Comment by iamzhuyi** [comment]
> 优化了一下头图体积(192kb -> 3kb)，加了点动画 ![logo-withAni](https://user-images.githubusercontent.com/22438240/258717075-1c071b29-c4d5-4f75-9ca6-3cdcf9b73151.svg)

还是胯下运球，可以，很细😂

**Comment by LegendarySSS** [comment]
你们醉嚎是在搞技术

**Comment by LikeDreamwalker** [comment]
> 优化了一下头图体积(192kb -> 3kb)，加了点动画 ![logo-withAni](https://user-images.githubusercontent.com/22438240/258717075-1c071b29-c4d5-4f75-9ca6-3cdcf9b73151.svg)

是不是可以给头加一个垂直的运动动画

**Comment by NWYLZW** [comment]
铁山靠？

**Comment by Sunshop** [comment]
> 单走一个6

难道是Kai哥

**Comment by lsrweb** [comment]
噗哈哈哈哈哈,哈哈哈哈哈笑死我了
![image](https://github.com/ikun-svelte/ikun-ui/assets/61956525/71e3cbd2-2b9b-437a-99b5-dca0c5ee7820)

**Comment by songzhanpeng** [comment]
![示例图片](https://songzhanpeng.github.io/ikun.svg)

**Comment by songzhanpeng** [comment]
![ikun](https://github.com/ikun-svelte/ikun-ui/assets/80727337/518a7585-223b-43f7-b032-e029daf4af51)

**Comment by songzhanpeng** [comment]
![ikun](https://github.com/ikun-svelte/ikun-ui/assets/80727337/907c33d1-407c-4e33-a1e5-28add91fdf74)
加个篮球

**Comment by shiyulong11** [comment]
> 优化了一下头图体积(192kb -> 3kb)，加了点动画 Optimized the header image volume (192kb -> 3kb) and added some animation  ![logo-withAni](https://user-images.githubusercontent.com/22438240/258717075-1c071b29-c4d5-4f75-9ca6-3cdcf9b73151.svg)

大佬，收下我的膝盖

**Comment by AfireHong** [comment]
我觉得这个中分头也可以再优化下

**Comment by linwu-hi** [comment]
> 优化了一下头图体积(192kb -> 3kb)，加了点动画 ![logo-withAni](https://user-images.githubusercontent.com/22438240/258717075-1c071b29-c4d5-4f75-9ca6-3cdcf9b73151.svg)

你是咋做到的

**Comment by baiwusanyu-c** [comment]
首页添加了动画，代码来自 @Soya-xy

**Comment by toplyb** [comment]
> 优化了一下头图体积(192kb -> 3kb)，加了点动画 ![logo-withAni](https://user-images.githubusercontent.com/22438240/258717075-1c071b29-c4d5-4f75-9ca6-3cdcf9b73151.svg)

泰苦辣

**Comment by tianmin94** [comment]
太6咯大家都

**Comment by tao1991123** [comment]
泰酷辣

**Comment by baiwusanyu-c** [comment]
spin和backtop添加了本issue动画

**Comment by quibbler01** [comment]
Awesome
