### ISSUE TITLE
The style of a disabled button

### ISSUE THREAD

**Issue by wangyewei** [ikun-svelte/ikun-ui#76]
### Description

As we are accustomed to, when a button becomes `disabled`, it's expected to change its `cursor` to 'not-allowed'.  Additionally, it should remove any `hover`, `active`, or `focus` styles, and possibly decrease its opacity.  However, you haven't implemented this.  Was this omission intentional according to your design?

![image](https://github.com/ikun-svelte/ikun-ui/assets/49926816/1b862fa5-86ff-4e0f-88b3-0ffac0dc5e05)

**Comment by baiwusanyu-c** [comment]
I will be implementing more styles for the buttons in the coming days
