### ISSUE TITLE
🎯 Short term plan（v0.0.9）

### ISSUE THREAD

**Issue by baiwusanyu-c** [ikun-svelte/ikun-ui#93]
### Description

# Enhance

## Input

| Enhance              | Status |
| -------------------- | ------ |
| Three sizes of Input | ✅ #246  |
| Search Input         | ✅     |
| Password Input       | ✅     |
| Textarea             |✅     |
| Textarea-maxCol      | ✅   |
| Textarea-minCol      | ✅    |
| Textarea-autoSize    | ✅     |

## Select

TODO

## ✅ Button

| Enhance                            | Status |
| ---------------------------------- | ------ |
| Three sizes of Button              | ✅     |
| ghost of Button                    | ✅     |
| click animation                    | ✅ |
| disabled style                     | ✅     |
| fill style (Background color fill) | ✅    |
| isBorder                           | ✅     |
| Button group                       | ✅     |

## ✅ CheckBox

| Enhance        | Status |
| -------------- | ------ |
| CheckBox Group | ✅     |
| Check All      | ✅     |
| Indeterminate  | ✅     |

## Radio
| Enhance        | Status |
| -------------- | ------ |
| Radio Group | ✅     |

## ✅Collapse

| Enhance       | Status |
| ------------- | ------ |
| ShowArrow     | ✅     |
| accordion     | ✅     |

## ✅Tag

| Enhance    | Status |
| ---------- | ------ |
| bgColor    | ✅  |
| textColor  | ✅ |
| closable | ✅  |
| onClose    | ✅ |
| icon       | ✅  |
| suffixIcon | ✅  |
| isBorder   | ✅ |

# ✅ Unit test

| Component     | Status |
| ------------- | ------ |
| KButton       | ✅     |
| KCheckbox     | ✅     |
| KCollapse     | ✅     |
| KDrawer       | ✅    |
| KEyeDropper   | ⚠     |
| KIcon         | ✅     |
| KInput        | ✅     |
| KMask         | ✅     |
| KMessage      | ✅     |
| KMessageBox   | ✅    |
| KModal        | ✅ |
| KNotification | ✅ |
| KPopover      | ✅ #150  |
| KSelect       | ✅      |
| KSwitch       | ✅     |
| KTag          | ✅     |
| KSpin         | ✅     |
| KTooltip      |  ✅    |

# New Component

| Component   | Status |
| ----------- | ------ |
| KInfinite   | ✅     |
| KGrid       | ✅     |
| KLayout     | ✅     |
| KBreadcrumb | ✅     |
| KRadio      | ✅     |
| KRate       | ✅ #177  |
| KAvatar     | ✅ #115  |
| KBadge      | ✅   |
| KProgress   | ✅  #183    |
| KSpin       | ✅ #118 |
| KLink       | ✅     |
| KBacktop    | ✅  #138 |
| KPopconfirm | ✅ |
| KForm| 🚧（next version） #108 |
| KBreadcrumb | ✅ #123 |
| KEllipsis | ✅ #248  |
| KContextmenu | ✅ #262 |
| KSlider| ✅ #141 |
| KAlert| ✅ #175 |
| KDivider| ✅#265 |
> More components are planned...

**Comment by baiwusanyu-c** [comment]
状态 为 🎯 说明我在写

**Comment by vtrbo** [comment]
> 状态 为 🎯 说明我在写

可以的，这样的话不容易做重复工作

**Comment by so1ve** [comment]
萌新第一次搞开源，不知道这个项目怎么搞😩

**Comment by baiwusanyu-c** [comment]
> 萌新第一次搞开源，不知道这个项目怎么搞😩

入老师，求求您给我来个pr可以吗🥵🥵

**Comment by jobsofferings** [comment]
入老师可还行

**Comment by moushicheng** [comment]
KFrom需要不，我两天前提了个pr，但这里没看到，工作日可能搞不了，这周六继续搞

**Comment by baiwusanyu-c** [comment]
> KFrom需要不，我两天前提了个pr，但这里没看到，工作日可能搞不了，这周六继续搞

先留着，慢慢看

**Comment by Innei** [comment]
萌新第一次搞开源，不知道这个项目怎么搞😩

**Comment by baiwusanyu-c** [comment]
> 萌新第一次搞开源，不知道这个项目怎么搞😩

拾神！您~🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️

**Comment by pkc918** [comment]
好多大佬发🤩

**Comment by so1ve** [comment]
> 拾神！您~🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️

白雾鸽鸽我要当ikun😫😫

**Comment by songjianet** [comment]
萌新第一次搞svelte，不知道怎么弄

**Comment by Alfred-Skyblue** [comment]
入门求带🥵

**Comment by BugFactory9527** [comment]
我的star和fork为了giegie留
